name: eslint-check

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: linter check
      - run: npm ci
      - run: make lint
