name: eslint-check

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
      - name: get repo code
        uses: actions/checkout@v3
      - name: install dep-s
        run: npm ci
      - name: linter check
        run: make lint
